// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe9NDbUMfXEAjlp4hQHkE_NC9TnkuAzCM',
    appId: '1:84962114902:web:cd6bad701e6b747d7f2af7',
    messagingSenderId: '84962114902',
    projectId: 'flutterjellyfish',
    authDomain: 'flutterjellyfish.firebaseapp.com',
    storageBucket: 'flutterjellyfish.firebasestorage.app',
    measurementId: 'G-44LH0C8CM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ6mzYyKk7h_sRW6ovnGwebPFFEUZbRUA',
    appId: '1:84962114902:android:46d92c4850322f4b7f2af7',
    messagingSenderId: '84962114902',
    projectId: 'flutterjellyfish',
    storageBucket: 'flutterjellyfish.firebasestorage.app',
  );

}